import org.jetbrains.compose.desktop.application.dsl.TargetFormat

plugins {
    kotlin("jvm")
    id("org.jetbrains.kotlin.plugin.compose")
    id("org.jetbrains.compose")
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}

// Single source of truth for the app version. Feeds both the macOS
// bundle (packageVersion, below) and the string the UI shows, so a
// screenshot of the About box can never disagree with the .app it
// came out of. Bump it here and nowhere else.
val appVersion = "1.0.1"

// Generates BuildInfo.kt into a source dir Kotlin compiles alongside
// src/main/kotlin. The alternative — reading Implementation-Version off
// the jar manifest — returns null under `gradlew run`, where classes
// are loaded from a directory and there is no manifest to read.
val generateBuildInfo by tasks.registering {
    val outDir = layout.buildDirectory.dir("generated/buildinfo")
    inputs.property("appVersion", appVersion)
    outputs.dir(outDir)
    doLast {
        val file = outDir.get().asFile.resolve("com/fc/safe/desktop/BuildInfo.kt")
        file.parentFile.mkdirs()
        file.writeText(
            """
            package com.fc.safe.desktop

            /**
             * Generated by the Gradle `generateBuildInfo` task from
             * `appVersion` in app-desktop/build.gradle.kts. Do not edit —
             * edits are overwritten on the next build.
             */
            object BuildInfo {
                const val VERSION = "$appVersion"
            }

            """.trimIndent()
        )
    }
}

kotlin.sourceSets["main"].kotlin.srcDir(generateBuildInfo)

dependencies {
    implementation(compose.desktop.currentOs)
    implementation(compose.materialIconsExtended)
    implementation(project(":platform-macos"))
    implementation("fc:FC-JDK:1.0-SNAPSHOT")

    // Voyager — stack-based navigation for Compose Desktop
    implementation("cafe.adriel.voyager:voyager-navigator:1.1.0-beta02")
    implementation("cafe.adriel.voyager:voyager-screenmodel:1.1.0-beta02")
    implementation("cafe.adriel.voyager:voyager-transitions:1.1.0-beta02")

    // Compose Desktop runs on the AWT/Swing event thread. Without this
    // module, Dispatchers.Main and everything derived from it throws
    // "Module with the Main dispatcher is missing" at runtime.
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-swing:1.9.0")
}

compose.desktop {
    application {
        mainClass = "com.fc.safe.desktop.MainKt"
        nativeDistributions {
            targetFormats(TargetFormat.Dmg)

            // jlink strips the runtime image to what it can see statically, and it
            // cannot see reflective/service loads: logback pulls in javax.naming and
            // sqlite-jdbc pulls in java.sql. Without these the packaged app dies at
            // startup with "Failed to launch JVM" — which never reproduces under
            // `gradlew run`, since that uses the full local JDK. From
            // `gradlew :app-desktop:suggestRuntimeModules`.
            //
            // jdk.charsets is the same story but fails later, not at startup:
            // ZXing's StringUtils static-inits with Charset.forName("SJIS")
            // (the QR spec's Shift_JIS mode), so the first QR we draw throws
            // ExceptionInInitializerError / UnsupportedCharsetException and
            // takes the AWT event thread — and the app — down with it.
            modules(
                "java.compiler",
                "java.instrument",
                "java.management",
                "java.naming",
                "java.security.jgss",
                "java.sql",
                "jdk.charsets",
                "jdk.unsupported",
            )

            packageName = "Safe"
            packageVersion = appVersion
            macOS {
                bundleID = "com.fc.safe.desktop"
                signing {
                    sign.set(true)
                    identity.set("CHANGYONG LIU (5768V787GP)")
                }
                notarization {
                    appleID.set(providers.environmentVariable("APPLE_ID"))
                    password.set(providers.environmentVariable("APPLE_APP_SPECIFIC_PASSWORD"))
                    teamID.set("5768V787GP")
                }
            }
        }
    }
}

// Phase 0 smoke test: FC-JDK key-gen + sign + verify on the combined classpath.
tasks.register<JavaExec>("smokeTest") {
    group = "verification"
    description = "Run FC-JDK crypto smoke test with Compose deps on classpath"
    mainClass.set("com.fc.safe.desktop.SmokeTestKt")
    classpath = sourceSets["main"].runtimeClasspath
}

// Phase 1 smoke test: DesktopApp lifecycle + EasyDB round-trip.
tasks.register<JavaExec>("phase1Smoke") {
    group = "verification"
    description = "Open DB context, write/read FcEntity, close, reopen, verify"
    mainClass.set("com.fc.safe.desktop.Phase1SmokeKt")
    classpath = sourceSets["main"].runtimeClasspath
}

// Phase 2 smoke test: AvatarMaker layer loading + composite.
tasks.register<JavaExec>("avatarSmoke") {
    group = "verification"
    description = "Composite a few avatars and dump PNGs under build/avatar-smoke"
    mainClass.set("com.fc.safe.desktop.AvatarSmokeKt")
    classpath = sourceSets["main"].runtimeClasspath
}

// Phase 2 backup interop smoke: base64 bundle + BackupCodec + password
// encrypt/decrypt symmetry (no WalletSession / no DB).
tasks.register<JavaExec>("backupInteropSmoke") {
    group = "verification"
    description = "Build + walk an Android-shaped export blob end to end"
    mainClass.set("com.fc.safe.desktop.BackupInteropSmokeKt")
    classpath = sourceSets["main"].runtimeClasspath
}

// Phase 2 TOTP smoke: RFC 6238 Appendix B test vectors against TotpUtil.
tasks.register<JavaExec>("totpSmoke") {
    group = "verification"
    description = "Validate TOTP output against RFC 6238 Appendix B vectors"
    mainClass.set("com.fc.safe.desktop.TotpSmokeKt")
    classpath = sourceSets["main"].runtimeClasspath
}

// Phase 2 secret-backup interop smoke: Android-shaped Secret export
// envelope + BackupCodec walk + CryptoDataStr decrypt round-trip.
tasks.register<JavaExec>("secretBackupInteropSmoke") {
    group = "verification"
    description = "Round-trip a secret through the Android-shaped export envelope"
    mainClass.set("com.fc.safe.desktop.SecretBackupInteropSmokeKt")
    classpath = sourceSets["main"].runtimeClasspath
}

// Make-QR round trip: split a payload, encode + rasterise every chunk,
// decode it back with the scan-side reader, and check the parts rejoin
// to the original. Also dumps build/qr-make-smoke.png.
tasks.register<JavaExec>("qrMakeSmoke") {
    group = "verification"
    description = "Round-trip payloads through QR chunking, encode and decode"
    mainClass.set("com.fc.safe.desktop.QrMakeSmokeKt")
    classpath = sourceSets["main"].runtimeClasspath
}

// Renders the scan-QR field variants off-screen to build/scan-field-smoke.png
// so the layout can be checked without clicking through every dialog.
tasks.register<JavaExec>("scanFieldRenderSmoke") {
    group = "verification"
    description = "Render ScanTextField / QrScanIconButton / CryptoIoBlock to a PNG"
    mainClass.set("com.fc.safe.desktop.ScanFieldRenderSmokeKt")
    classpath = sourceSets["main"].runtimeClasspath
}
